# render.yaml
services:
  - type: web
    name: rian-audio-sounds
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt && \
      python manage.py collectstatic --noinput && \
      python manage.py migrate
    startCommand: |
      python manage.py migrate && \
      python create_superuser.py && \
      gunicorn rian_backend.wsgi:application --log-file -
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: rian_backend.settings
      - key: DATABASE_URL
        fromDatabase:
          name: rian-db
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false   # set manually in Render dashboard
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

databases:
  - name: rian-db
    plan: free
