# Generated by Django 5.2.6 on 2025-09-15 09:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_category_image_alter_product_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Main product image (shown as thumbnail and hero)', max_length=255, null=True),
        ),
    ]
